default: &default
  adapter: postgresql
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>
  port: <%= ENV.fetch("DB_PORT") %>

development:
  <<: *default
  database: search_component_development

test:
  <<: *default
  database: search_component_test

production:
  adapter: postgresql
  database: search_component_production
  encoding: utf8