default: &default
  adapter: postgresql
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  encoding: utf8
  host: <%= ENV["DB_HOSTNAME"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: search_component_development

test:
  <<: *default
  database: search_component_test

production:
  adapter: postgresql
  database: search_component_production
  encoding: utf8